global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'archivestream-api'
    static_configs:
      - targets: ['api:3001']
    metrics_path: '/metrics'

  - job_name: 'archivestream-crawler'
    static_configs:
      - targets: ['crawler-us-east-1:9091']
    metrics_path: '/metrics'

  - job_name: 'archivestream-indexer'
    static_configs:
      - targets: ['indexer:9092']
    metrics_path: '/metrics'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'opensearch'
    static_configs:
      - targets: ['opensearch:9200']
